version: '3'

services:
  mariadb:
    image: mariadb:10.5
    container_name: bible_db
    hostname: "bible_db"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
        - ./curl_bible/.env
    environment:
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    restart: always
    ports:
      - 33060:3306
  
  curl_bible:
    image: curl_bible
    build:
      # Allows .env to be used by both Docker-Compose and the Python image
      context: ./curl_bible
    hostname: "curl_bible"
    container_name: curl_bible
    ports:
      - 10000:10000
    volumes:
      # Allow logs to be viewed without entering the container.
      # - ./logs:/usr/src/app/python/log
      - ./logs:/code/app/log
    restart: always
