version: '3'

services:
  mariadb:
    image: mariadb:10.5
    container_name: bible_db
    hostname: "bible_db"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
        - ./docker/.env
    environment:
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    restart: always
  
  curl_bible:
    image: curl_bible
    build:
      # Allows .env to be used by both Docker-Compose and the Python image
      context: ./docker
    hostname: "curl_bible"
    container_name: curl_bible
    ports:
      - 10000:10000
      - 5001:5001
    volumes:
      # Allow logs to be viewed without entering the container.
      - ./logs:/usr/src/app/logs
      - ./docker:/usr/src/app/backup
    restart: always