name: Test, Publish Image, and Deploy

on: [push]

jobs:
  test-code:
    runs-on: ubuntu-latest
    container: quay.io/connorricotta/ubuntu_node:latest
    strategy:
      matrix:
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make venv
        run: mkdir .venv

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          chmod a+r .env

      - name: Pipenv Install (with cache)
        uses: https://github.com/kevincobain2000/action-cache-http@v2
        with:
          version: ${{ matrix.python-version }}
          lock_file: Pipfile.lock
          install_command: pipenv install -r requirements_cicd.txt
          destination_folder: .venv
          cache_http_api: ${{ secrets.CACHE_URL }}
          basic_auth_username: ${{ secrets.CACHE_AUTH_USERNAME }}
          basic_auth_password: ${{ secrets.CACHE_AUTH_PASSWORD }}

      - name: Run tests
        run: |
          pipenv run pytest
          pipenv run flake8 .
          pipenv run bandit .
          pipenv run isort .
          pipenv run black .

      - run: echo "This job's status is ${{ job.status }}."

  publish:
    # Only run if the push has a new version and the previous tests pass.
    needs: test-code
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container: quay.io/connorricotta/ubuntu_node:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull tag from git
        uses: https://github.com/WyriHaximus/github-action-get-previous-tag@v1
        id: tag

      - name: "Login to quay.io"
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login ${{ secrets.IMAGE_REGISTRY }} --password-stdin --username ${{ secrets.QUAY_USERNAME }}

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v2

      - name: install buildx
        id: buildx
        uses: https://github.com/crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: "Build new Docker Image"
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:${{ steps.tag.outputs.tag }} -t ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:latest --push .

      - name: Make SSH key
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: SSH to test
        run: |
          ssh -o "StrictHostKeyChecking no" -t -i ssh_key ${{ secrets.DEPLOY_HOST }} '
            cd ${{ secrets.DEPLOY_PATH }}/${{ gitea.repository }}
            git pull
            git fetch --prune
            docker pull ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:latest
            docker-compose down && docker-compose up -d
          '

      - run: echo "This job's status is ${{ job.status }}."
