name: Test Docker login

# on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/connorricotta/ubuntu_node:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull tag from git
        uses: https://github.com/WyriHaximus/github-action-get-previous-tag@v1
        id: tag

      - name: "Login to quay.io"
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login ${{ secrets.IMAGE_REGISTRY }} --password-stdin --username ${{ secrets.QUAY_USERNAME }}

      - name: "Build new Docker Image"
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:${{ steps.tag.outputs.tag }} -t ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:latest --push .

      # docker buildx build --platform linux/arm64 -t ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:${{ steps.tag.outputs.tag }} -t ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:latest --push .
      # - name: "Push new docker images"
      #   run: |
      #     docker push ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:${{ steps.tag.outputs.tag }}
      #     docker push ${{ secrets.IMAGE_REGISTRY }}/${{ gitea.repository }}:latest

      - run: echo "This job's status is ${{ job.status }}."
