name: Test Deploy key

# on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: connorricotta/ubuntu_node:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make SSH key
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Pull tag from git
        uses: https://github.com/WyriHaximus/github-action-get-previous-tag@v1
        id: tag

      - name: SSH to test
        run: |
          ssh -o "StrictHostKeyChecking no" -t -i ssh_key ${{ secrets.DEPLOY_HOST }} '
            cd ${{ secrets.DEPLOY_PATH }}/${{ gitea.repository }}
            git pull
            git fetch --prune
            docker pull ${{ gitea.repository }}:${{ steps.tag.outputs.tag }}
            docker-compose down && docker-compose up -d
          '

      - run: echo "This job's status is ${{ job.status }}."
